const GENZ_REGISTRY_SHEET_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ9iId2u2Nk_AApB9YrQnPeHJYgZC-niVIOFqvMlXw4vSDHtraz3zNC-lg0jodPiV9g71ItkiNc-us1';
const GENZ_REGISTRY_SHEET_XLSX_URL = `${GENZ_REGISTRY_SHEET_URL}/pub?output=xlsx`;
const GENZ_REGISTRY_SHEET_WEB_URL = `${GENZ_REGISTRY_SHEET_URL}/pubhtml`;

module.exports = {
  GENZ_REGISTRY_SHEET_URL,
  GENZ_REGISTRY_SHEET_XLSX_URL,
  GENZ_REGISTRY_SHEET_WEB_URL
};
